[package]
name = "frivolous"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.86", features = ["backtrace"] }
derive_more = "0.99.17"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
